#!/usr/bin/env python3
"""Build the text.match list-consumption probe (PHASE 11, plan 11-07 Task 2).

THE ONE QUESTION
----------------
`is.workflow.actions.text.match` publishes a LIST ("Matches").  When that list-valued
output is consumed, which shape yields the matched section as a usable string?

    Shape A  (what the engine does today):  match -> gettext -> string
    Shape B  (the in-repo precedent, tools/build_sentient.py audit_block()):
             match -> getitemfromlist[First Item] -> gettext -> string

Neither shape is corpus-attested.  Re-taken this session over all 19 golden shortcuts:
this identifier's output is consumed by getgroup x7, conditional x5, setvariable x1,
count x1, detect.text x1 -- and by `gettext` ZERO times and `getitemfromlist` ZERO times.
So rung 1 genuinely cannot settle it, which is why this probe exists.

WHY THERE IS NO Show Alert IN HERE
----------------------------------
Plan 11-07 Task 2 asks for three Show Alerts.  `.claude/CLAUDE.md` §9 records, from spike
010, that **Show Alert modals accept neither a synthesized tap nor a hardware Return** --
the run wedges permanently at the first one -- and instructs that simulator-bound probes
be built with NO BLOCKING UI.  Three alerts would wedge three times and read out nothing.
This probe therefore writes ALL results into ONE clipboard payload, recovered off-device
with `xcrun simctl pbpaste`, which is non-blocking and needs no synthesized input at all.
Recorded as a deviation in docs/BUILD-NOTES.md.

RUNG DISCIPLINE
---------------
Deliberately inside rung 2's competence: no Notes action, no model, no automation, no
real-hardware environmental behaviour.  The fixture is held inline in a Text action, so
nothing is read from the Control Room Note.  This settles runtime variable resolution and
list-consumption typing ONLY -- it says nothing whatever about device behaviour.
"""
import pathlib
import plistlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "tools"))

from build_state_engine import (  # noqa: E402
    PANIC_ESCAPE_SECTION_PATTERN,
    action,
    comment,
    end_if,
    if_block,
    otherwise,
    output,
    set_var,
    text_token,
    uid,
    variable,
)

OUT = pathlib.Path(__file__).resolve().parent / "text-match-consumption-probe.xml"

# The exact line panic_escape_branch() runs its condition-99 contains test against.
# Imported in spirit from the generator; restated here so the probe is self-contained
# and can be re-run after the generator moves on.
REMOVED_LINE = "Panic Escape: OFF"

# The fixture reproduces the Note's real shape: the PANIC ESCAPE heading, the setting
# line in its REMOVED position, and the MY PHONE, ON PURPOSE heading that bounds the
# pattern.  PANIC_ESCAPE_SECTION_PATTERN matches from the first heading up to (but not
# including) the second.
FIXTURE = (
    "## CONTROL ROOM\n"
    "Some preamble that must never be captured.\n"
    "## PANIC ESCAPE\n"
    f"{REMOVED_LINE}\n"
    "Set this line to ON to restore it.\n"
    "## MY PHONE, ON PURPOSE\n"
    "Trailing content that must never be captured.\n"
)


def build():
    fixture_id = uid()
    match_a, match_b = uid(), uid()
    text_a = uid()
    first_b, text_b = uid(), uid()
    report = uid()

    a = [
        comment("--- TEXT MATCH CONSUMPTION PROBE ---\n"
                "- One question: which consumption shape yields the matched section as a usable string.\n"
                "- Fixture is inline; no Note, no model, no automation is touched.\n"
                "- Results leave via the clipboard, never a modal, so the run cannot wedge."),
        comment("Shortcuts generated by Shortcuts Playground.\n"
                "Probe for PROSOCHE plan 11-07 Task 2; not a shipped artifact."),
        action("is.workflow.actions.gettext", UUID=fixture_id, WFTextActionText=FIXTURE),

        # --- Shape A: match -> gettext ------------------------------------------------
        comment("Shape A, the engine's current chain:\n"
                "- Match the bounded section pattern over the inline fixture.\n"
                "- Coerce the list-valued output straight to Text.\n"
                "- Record whatever that yields."),
        action("is.workflow.actions.text.match", UUID=match_a,
               WFMatchTextPattern=PANIC_ESCAPE_SECTION_PATTERN,
               text=output(fixture_id, "Text")),
        action("is.workflow.actions.gettext", UUID=text_a,
               WFTextActionText=output(match_a, "Matches")),
        set_var("Shape A Result", output(text_a, "Text")),

        # --- Shape B: match -> getitemfromlist[First Item] -> gettext -----------------
        comment("Shape B, the in-repo precedent from build_sentient.py audit_block():\n"
                "- Same match over the same fixture.\n"
                "- Take the First Item explicitly before coercing to Text.\n"
                "- The item picker holds a literal enum case, per axis 4."),
        action("is.workflow.actions.text.match", UUID=match_b,
               WFMatchTextPattern=PANIC_ESCAPE_SECTION_PATTERN,
               text=output(fixture_id, "Text")),
        action("is.workflow.actions.getitemfromlist", UUID=first_b,
               WFItemSpecifier="First Item", WFInput=output(match_b, "Matches")),
        action("is.workflow.actions.gettext", UUID=text_b,
               WFTextActionText=output(first_b, "Item from List")),
        set_var("Shape B Result", output(text_b, "Text")),
    ]

    # --- The test the removal path actually depends on --------------------------------
    # panic_escape_branch() gates on condition 99 (contains) over Shape A's output
    # against the removed-position line.  If Shape A does not resolve, this reads FALSE
    # and the user is told "Nothing was changed" on the path meant to remove the bypass.
    contains_g, contains_if = if_block("Shape A Result", 99, string=REMOVED_LINE)
    true_id, false_id = uid(), uid()
    a += [
        comment("The load-bearing gate:\n"
                "- Condition 99 (contains) over Shape A's output, against the removed-position line.\n"
                "- This is the exact test panic_escape_branch() runs.\n"
                "- FALSE here is the silent-wrong-success defect this plan exists to close."),
        contains_if,
        action("is.workflow.actions.gettext", UUID=true_id,
               WFTextActionText="TRUE - Shape A output contains the removed-position line"),
        set_var("Contains Verdict", output(true_id, "Text")),
        otherwise(contains_g),
        action("is.workflow.actions.gettext", UUID=false_id,
               WFTextActionText="FALSE - Shape A output does NOT contain the removed-position line"),
        set_var("Contains Verdict", output(false_id, "Text")),
        end_if(contains_g),
    ]

    # --- One non-blocking readout -----------------------------------------------------
    a += [
        comment("Single clipboard readout:\n"
                "- All three results are concatenated into one payload.\n"
                "- Recovered off-device with xcrun simctl pbpaste; no modal, no tap needed.\n"
                "- Delimiters make an EMPTY result distinguishable from a missing one."),
        action("is.workflow.actions.gettext", UUID=report,
               WFTextActionText=text_token([
                   ("PROBE-BEGIN\n[SHAPE_A]<<", None), ("", "Shape A Result"), (">>\n[SHAPE_B]<<", None),
                   ("", "Shape B Result"), (">>\n[CONTAINS]<<", None), ("", "Contains Verdict"),
                   (">>\nPROBE-END", None),
               ])),
        action("is.workflow.actions.setclipboard", WFInput=output(report, "Text")),
    ]
    return a


def main():
    actions = build()
    data = {
        "WFWorkflowActions": actions,
        "WFWorkflowClientVersion": "1300",
        "WFWorkflowMinimumClientVersion": 900,
        "WFWorkflowMinimumClientVersionString": "900",
        "WFWorkflowIcon": {
            "WFWorkflowIconGlyphNumber": 59511,
            "WFWorkflowIconStartColor": 946986751,
        },
        "WFWorkflowImportQuestions": [],
        "WFWorkflowInputContentItemClasses": [],
        "WFWorkflowOutputContentItemClasses": [],
        "WFWorkflowTypes": [],
        "WFWorkflowHasOutputFallback": False,
    }
    OUT.write_bytes(plistlib.dumps(data, fmt=plistlib.FMT_XML, sort_keys=False))
    print(f"built {OUT} ({len(actions)} actions)")


if __name__ == "__main__":
    main()
