#!/usr/bin/env python3
"""Negative control: prove the two Set Brightness failure modes are DISTINGUISHABLE.

WHY THIS EXISTS.  Running the coerced leg on the simulator produced:

    "Could Not Run Set Brightness -- There was a problem setting the brightness."

That is a CAPABILITY failure (the simulator has no backlight), not the PARAMETER failure
this project's own conventions name as the signature of an operand-type defect:

    "Please choose a value for each parameter in this action."

The tempting inference is "the coerced operand therefore resolved, because Shortcuts got
past parameter validation and reached the OS call."  That inference is plausible and it is
NOT evidence.  `.claude/CLAUDE.md` is explicit that misattributed failures have cost this
project multiple cycles, and its standing instruction is to READ THE ERROR TEXT rather than
the fact of an error.  So this control MEASURES the distinction instead of assuming it.

THE CONTROL.  One Set Brightness with NO operand at all -- `WFBrightness` simply absent.
If that reports the PARAMETER error while the coerced leg reported the CAPABILITY error,
then the two stages are observably different on this channel, and the coerced leg
demonstrably cleared parameter validation.  If it reports the SAME capability error, then
the channel cannot distinguish them at all, the inference above is unsupported, and the
run-time question must be recorded as untouched by rung 2 rather than partially answered.

Either outcome is a result.  That is the whole point of running it.

This is the same negative-control idiom `docs/phase9_self_check.py::negative_control()`
already uses to prove its coercion guard is load-bearing.

Run:  python3 .planning/spikes/010-coercion-at-a-direct-set-parameter/drafts/build_negative_control.py
"""

import pathlib
import plistlib

DRAFTS = pathlib.Path(__file__).resolve().parent
NAME = "PROSOCHE Coercion Negative Control"

actions = [
    {"WFWorkflowActionIdentifier": "is.workflow.actions.comment",
     "WFWorkflowActionParameters": {"WFCommentActionText":
        "SPIKE 010 NEGATIVE CONTROL -- ONE Set Brightness with NO value.\n"
        "\n"
        "Not a probe of the coercion. A probe of the CHANNEL: does an unfilled parameter\n"
        "report differently from a device that cannot change its brightness? The coerced\n"
        "leg reported 'There was a problem setting the brightness'. If this one reports\n"
        "'Please choose a value for each parameter in this action' instead, the two\n"
        "stages are observably distinct and the coerced leg cleared parameter validation.\n"
        "If it reports the same message, the channel cannot tell them apart and no\n"
        "run-time conclusion may be drawn from either."}},
    {"WFWorkflowActionIdentifier": "is.workflow.actions.comment",
     "WFWorkflowActionParameters": {"WFCommentActionText":
        "Shortcuts generated by Shortcuts Playground. May contain mistakes. Always check "
        "the shortcut's actions first.\n"
        "\n"
        "This shortcut was created via the following user prompt:\n"
        "\n"
        "> Build a one-action negative control holding a Set Brightness with no value, so\n"
        "> the unfilled-parameter failure can be told apart from the device-capability\n"
        "> failure a simulator produces."}},
    # The whole control: Set Brightness with its operand ABSENT.
    {"WFWorkflowActionIdentifier": "is.workflow.actions.setbrightness",
     "WFWorkflowActionParameters": {"ShowWhenRun": False}},
]

root = {
    "WFWorkflowActions": actions,
    "WFWorkflowClientVersion": "2700.0.4",
    "WFWorkflowHasOutputFallback": False,
    "WFWorkflowIcon": {"WFWorkflowIconGlyphNumber": 61520,
                       "WFWorkflowIconStartColor": 4282601983},
    "WFWorkflowInputContentItemClasses": [],
    "WFWorkflowMinimumClientVersion": 900,
    "WFWorkflowMinimumClientVersionString": "900",
    "WFWorkflowName": NAME,
    "WFWorkflowOutputContentItemClasses": [],
    "WFWorkflowTypes": [],
}

out = DRAFTS / f"{NAME}.xml"
out.write_bytes(plistlib.dumps(root, fmt=plistlib.FMT_XML, sort_keys=False))
print(f"wrote {out} ({len(actions)} actions)")
