#!/usr/bin/env python3
"""
PROSOCHE Probe 5 - Input Echo.

Diagnostic artifact for debug session `open-routing-sequence-error`, cycle 6.

PURPOSE
-------
Decide the partition that five cycles have assumed rather than tested:

  (A) the Personal Automation's Run Shortcut handoff DOES deliver "OPEN" to the
      invoked shortcut, so the defect lives inside PROSOCHE's OPEN pipeline; or
  (B) the failure happens AT OR ABOVE the handoff, so no PROSOCHE action ever runs
      and every plist-side theory from cycles 1-5 was aimed at the wrong layer.

DESIGN NOTES (why it is shaped like this)
-----------------------------------------
* The normalisation chain (Get Text -> Trim Whitespace -> Change Case) is copied
  byte-for-byte in shape from PROSOCHE's own device-proven actions 84-86, including
  the WFTextTokenString envelopes and the exact producing-action output names
  ("Text", "Trimmed Text"). Nothing here is a new or unverified action shape.
* The root keys mirror PROSOCHE's exactly on the two that govern input handoff -
  WFWorkflowInputContentItemClasses = ["WFStringContentItem"] and
  WFWorkflowHasShortcutInputVariables = true - so the probe is a faithful test of
  the same handoff rather than of a differently-declared shortcut.
* The alert reports BOTH the raw and the normalised value inside brackets, so the
  user reads literal characters instead of judging whether a UI field "looks set".
* attachmentsByRange offsets are COMPUTED from the assembled string, never hand
  counted - out-of-bounds ranges can crash Shortcuts on import.
"""

import plistlib
import uuid
from pathlib import Path

OBJ = "￼"  # OBJECT REPLACEMENT CHARACTER - the one-character attachment placeholder

HERE = Path(__file__).resolve().parent
OUT_XML = HERE / "05-input-echo.xml"
NAME = "PROSOCHE Probe 5 - Input Echo"


def token_string(parts):
    """Build a WFTextTokenString from ``parts``: str literals and token dicts.

    Offsets are derived from the assembled string so they cannot drift out of
    sync with the text, which is the documented cause of import crashes.
    """
    text = ""
    attachments = {}
    for part in parts:
        if isinstance(part, str):
            text += part
        else:
            attachments["{%d, 1}" % len(text)] = part
            text += OBJ
    return {
        "Value": {"string": text, "attachmentsByRange": attachments},
        "WFSerializationType": "WFTextTokenString",
    }


def output(uuid_str, name):
    return {"OutputUUID": uuid_str, "OutputName": name, "Type": "ActionOutput"}


def action(identifier, params):
    return {
        "WFWorkflowActionIdentifier": identifier,
        "WFWorkflowActionParameters": params,
    }


def build():
    u_get = str(uuid.uuid4()).upper()
    u_trim = str(uuid.uuid4()).upper()
    u_case = str(uuid.uuid4()).upper()

    actions = [
        action(
            "is.workflow.actions.comment",
            {
                "WFCommentActionText": (
                    "PROSOCHE Probe 5 - Input Echo.\n\n"
                    "Temporary diagnostic. Point the App Is Opened automation's "
                    "Run Shortcut at THIS shortcut, open a watched app, and report "
                    "the two bracket lines verbatim."
                )
            },
        ),
        action(
            "is.workflow.actions.comment",
            {
                "WFCommentActionText": (
                    "Shortcuts generated by Shortcuts Playground. May contain "
                    "mistakes. Always check the shortcut's actions first.\n\n"
                    "This shortcut was created from the following build "
                    "objective:\n\n"
                    "> Receive the Shortcut Input handed over by a Personal "
                    "Automation's Run Shortcut action, normalise it exactly the "
                    "way PROSOCHE does, and show both the raw and the normalised "
                    "value so a human can read them literally.\n"
                )
            },
        ),
        # 1: raw Shortcut Input -> text.   Mirrors PROSOCHE action 84.
        action(
            "is.workflow.actions.gettext",
            {
                "UUID": u_get,
                "WFTextActionText": token_string([{"Type": "ExtensionInput"}]),
            },
        ),
        # 2: trim.                          Mirrors PROSOCHE action 85.
        action(
            "is.workflow.actions.text.trimwhitespace",
            {
                "UUID": u_trim,
                "WFInput": token_string([output(u_get, "Text")]),
            },
        ),
        # 3: uppercase.                     Mirrors PROSOCHE action 86.
        action(
            "is.workflow.actions.text.changecase",
            {
                "UUID": u_case,
                "text": token_string([output(u_trim, "Trimmed Text")]),
                "WFCaseType": "UPPERCASE",
            },
        ),
        action(
            "is.workflow.actions.comment",
            {
                "WFCommentActionText": (
                    "Echo both values back inside brackets so the result is read "
                    "literally rather than judged from a UI field. [OPEN] on the "
                    "normalised line means the Run Shortcut handoff delivers input; "
                    "[] on both lines means it does not."
                )
            },
        ),
        # 4: echo both values back to the user.
        action(
            "is.workflow.actions.alert",
            {
                "WFAlertActionTitle": "PROBE 5 - INPUT ECHO",
                "WFAlertActionMessage": token_string(
                    [
                        "RAW        [",
                        output(u_get, "Text"),
                        "]\nNORMALISED [",
                        output(u_case, "Text"),
                        "]\n\nReport both bracket lines exactly as shown.\n"
                        "[OPEN] means the handoff works.\n"
                        "[] means no input arrived.",
                    ]
                ),
            },
        ),
    ]

    return {
        "WFWorkflowActions": actions,
        "WFWorkflowClientVersion": "2700.0.4",
        "WFWorkflowHasOutputFallback": False,
        "WFWorkflowHasShortcutInputVariables": True,
        "WFWorkflowIcon": {
            "WFWorkflowIconGlyphNumber": 59856,
            "WFWorkflowIconStartColor": 4251333119,
        },
        # These two are the load-bearing mirror of PROSOCHE's own root keys.
        "WFWorkflowInputContentItemClasses": ["WFStringContentItem"],
        "WFWorkflowMinimumClientVersion": 900,
        "WFWorkflowMinimumClientVersionString": "900",
        "WFWorkflowName": NAME,
        "WFWorkflowOutputContentItemClasses": [],
        "WFWorkflowTypes": [],
    }


if __name__ == "__main__":
    OUT_XML.write_bytes(plistlib.dumps(build(), fmt=plistlib.FMT_XML))
    print("wrote", OUT_XML)
